services:
  microservice-b:
    image: quarkus/microservice-b-jvm:v1
    ports:
      - "8081:8080"
    depends_on:
      - db-dogs
  db-dogs:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dogs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5435:5432
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
